/*
 * Copyright (C) 2014 Voipac. All Rights Reserved.
 * Copyright (C) 2012-2014 Freescale Semiconductor, Inc. All Rights Reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _BOARD_MX6Q_REX_H
#define _BOARD_MX6Q_REX_H
#include <mach/iomux-mx6q.h>

static iomux_v3_cfg_t mx6q_rex_pads[] = {
	/* AUDMUX */
	MX6Q_PAD_CSI0_DAT4__AUDMUX_AUD3_TXC,
	MX6Q_PAD_CSI0_DAT5__AUDMUX_AUD3_TXD,
	MX6Q_PAD_CSI0_DAT6__AUDMUX_AUD3_TXFS,
	MX6Q_PAD_CSI0_DAT7__AUDMUX_AUD3_RXD,

	/* CCM  */
	MX6Q_PAD_GPIO_0__CCM_CLKO,		/* SGTL500 sys_mclk */

	/* ECSPI2 */
	MX6Q_PAD_DISP0_DAT16__ECSPI2_MOSI,
	MX6Q_PAD_DISP0_DAT17__ECSPI2_MISO,
	MX6Q_PAD_DISP0_DAT19__ECSPI2_SCLK,
	MX6Q_PAD_DISP0_DAT18__GPIO_5_12,	/* CS */

	/* ECSPI3 */
	MX6Q_PAD_DISP0_DAT1__ECSPI3_MOSI,
	MX6Q_PAD_DISP0_DAT2__ECSPI3_MISO,
	MX6Q_PAD_DISP0_DAT0__ECSPI3_SCLK,
	MX6Q_PAD_DISP0_DAT5__GPIO_4_26,		/* CS */

	/* ENET */
	MX6Q_PAD_ENET_MDIO__ENET_MDIO,
	MX6Q_PAD_ENET_MDC__ENET_MDC,
	MX6Q_PAD_RGMII_TXC__ENET_RGMII_TXC,
	MX6Q_PAD_RGMII_TD0__ENET_RGMII_TD0,
	MX6Q_PAD_RGMII_TD1__ENET_RGMII_TD1,
	MX6Q_PAD_RGMII_TD2__ENET_RGMII_TD2,
	MX6Q_PAD_RGMII_TD3__ENET_RGMII_TD3,
	MX6Q_PAD_RGMII_TX_CTL__ENET_RGMII_TX_CTL,
	MX6Q_PAD_ENET_REF_CLK__ENET_TX_CLK,
	MX6Q_PAD_RGMII_RXC__ENET_RGMII_RXC,
	MX6Q_PAD_RGMII_RD0__ENET_RGMII_RD0,
	MX6Q_PAD_RGMII_RD1__ENET_RGMII_RD1,
	MX6Q_PAD_RGMII_RD2__ENET_RGMII_RD2,
	MX6Q_PAD_RGMII_RD3__ENET_RGMII_RD3,
	MX6Q_PAD_RGMII_RX_CTL__ENET_RGMII_RX_CTL,
	MX6Q_PAD_ENET_TX_EN__GPIO_1_28,		/* Micrel RGMII Phy Interrupt R */
	MX6Q_PAD_ENET_RXD1__GPIO_1_26,		/* Micrel RGMII Phy Interrupt */
	MX6Q_PAD_ENET_CRS_DV__GPIO_1_25,	/* RGMII reset */

	/* LED */
	MX6Q_PAD_GPIO_2__GPIO_1_2,		/* user defined red led */

	/* HDMI */
	MX6Q_PAD_KEY_ROW2__HDMI_TX_CEC_LINE,

	/* I2C1, SGTL5000 */
	MX6Q_PAD_CSI0_DAT9__I2C1_SCL,
	MX6Q_PAD_CSI0_DAT8__I2C1_SDA,

	/* I2C2, HDMI, TSC2007 */
	MX6Q_PAD_KEY_COL3__I2C2_SCL,
	MX6Q_PAD_KEY_ROW3__I2C2_SDA,

	/* I2C3, LVDS */
	MX6Q_PAD_EIM_D17__I2C3_SCL,
	MX6Q_PAD_EIM_D18__I2C3_SDA,

	/* I2C4 */
	MX6Q_PAD_NANDF_WP_B__GPIO_6_9,		/* SCL, TSC INT */
	MX6Q_PAD_NANDF_CS3__GPIO_6_16,		/* SDA, CPU INT */

	/* DISP_PWM */
	MX6Q_PAD_SD1_DAT3__PWM1_PWMO,		/* GPIO1[21] */

	/* SYSTEM */
	MX6Q_PAD_EIM_A25__GPIO_5_2,  		/* RESET */

	/* UART1 for debug */
	MX6Q_PAD_CSI0_DAT10__UART1_TXD,
	MX6Q_PAD_CSI0_DAT11__UART1_RXD,
	MX6Q_PAD_EIM_D19__UART1_CTS,
	MX6Q_PAD_EIM_D20__UART1_RTS,
	MX6Q_PAD_EIM_D25__UART1_DSR,
	MX6Q_PAD_EIM_D24__UART1_DTR,
	MX6Q_PAD_EIM_D23__UART1_DCD,
	MX6Q_PAD_EIM_EB3__UART1_RI,

	/* UART2 */
	MX6Q_PAD_SD4_DAT7__UART2_TXD,
	MX6Q_PAD_SD4_DAT4__UART2_RXD,

	/* USBOTG ID pin */
	MX6Q_PAD_GPIO_1__USBOTG_ID,

	/* USB power pin */
	MX6Q_PAD_EIM_D22__GPIO_3_22,		/* OTG */
	MX6Q_PAD_EIM_D31__GPIO_3_31,		/* HOST */

	/* USB OC pin */
	MX6Q_PAD_EIM_D21__USBOH3_USBOTG_OC,
	MX6Q_PAD_EIM_D30__USBOH3_USBH1_OC,

	/* USDHC2 */
	MX6Q_PAD_SD2_CLK__USDHC2_CLK_200MHZ,
	MX6Q_PAD_SD2_CMD__USDHC2_CMD_200MHZ,
	MX6Q_PAD_SD2_DAT0__USDHC2_DAT0_200MHZ,
	MX6Q_PAD_SD2_DAT1__USDHC2_DAT1_200MHZ,
	MX6Q_PAD_SD2_DAT2__USDHC2_DAT2_200MHZ,
	MX6Q_PAD_SD2_DAT3__USDHC2_DAT3_200MHZ,
	MX6Q_PAD_NANDF_D4__USDHC2_DAT4,
	MX6Q_PAD_NANDF_D5__USDHC2_DAT5,
	MX6Q_PAD_NANDF_D6__USDHC2_DAT6,
	MX6Q_PAD_NANDF_D7__USDHC2_DAT7,
	MX6Q_PAD_NANDF_D2__GPIO_2_2,		/* SD2_CD */
	MX6Q_PAD_NANDF_D3__GPIO_2_3,		/* SD2_WP */
	MX6Q_PAD_GPIO_6__USDHC2_LCTL,

	/* USDHC3 */
	MX6Q_PAD_SD3_CLK__USDHC3_CLK_200MHZ,
	MX6Q_PAD_SD3_CMD__USDHC3_CMD_200MHZ,
	MX6Q_PAD_SD3_DAT0__USDHC3_DAT0_200MHZ,
	MX6Q_PAD_SD3_DAT1__USDHC3_DAT1_200MHZ,
	MX6Q_PAD_SD3_DAT2__USDHC3_DAT2_200MHZ,
	MX6Q_PAD_SD3_DAT3__USDHC3_DAT3_200MHZ,
	MX6Q_PAD_NANDF_D0__GPIO_2_0,		/* SD3_CD */
	MX6Q_PAD_NANDF_D1__GPIO_2_1,		/* SD3_WP */

	/* PCIE */
	MX6Q_PAD_CSI0_DATA_EN__GPIO_5_20,	/* PCIE_WAKE */

	/* WDOG */
	MX6Q_PAD_DISP0_DAT8__WDOG1_WDOG_B,
};

static iomux_v3_cfg_t mx6q_rex_hdmi_ddc_pads[] = {
	MX6Q_PAD_KEY_COL3__HDMI_TX_DDC_SCL, 	/* HDMI DDC SCL */
	MX6Q_PAD_KEY_ROW3__HDMI_TX_DDC_SDA, 	/* HDMI DDC SDA */
};

static iomux_v3_cfg_t mx6q_rex_i2c2_pads[] = {
	MX6Q_PAD_KEY_COL3__I2C2_SCL,		/* I2C2 SCL */
	MX6Q_PAD_KEY_ROW3__I2C2_SDA,		/* I2C2 SDA */
};
#endif
